name: Publish Packages

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build viper-react
        run: bun run react:build

      - name: Build viper-vue
        run: bun run vue:build

      - name: Setup npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish viper-react
        run: cd packages/viper-react && npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish viper-vue
        run: cd packages/viper-vue && npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish vite-plugin-viper
        run: cd packages/vite-plugin-viper && npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
